version: "3"
services:
  osy-client:
    build:
      context: .
      dockerfile: osy-client.dockerfile
    depends_on:
      - osy-server
    ports:
      - "3000:5000"
    networks:
      - osy-network
  osy-server:
    build:
      context: .
      dockerfile: osy-server.dockerfile
    restart: always
    depends_on:
      - osy-db
    network_mode: service:osy-db

  osy-db:
    image: mariadb:latest
    restart: always
    ports:
      - "3001:3001"
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $REACT_APP_PASS
      MYSQL_DATABASE: $REACT_APP_DB
      MYSQL_ROOT_HOST: "%"
    networks:
      - osy-network
networks:
  osy-network:
    driver: bridge
